import Anthropic from '@anthropic-ai/sdk';
import { config } from '../../config/secrets.js';
import logger from '../../utils/logger.js';
import { buildCopyPrompt } from './copywriterPrompts.js';

const anthropic = new Anthropic({
  apiKey: config.ai.anthropic
});

// Existing helper function
function extractJsonFromMarkdown(text) {
  const match = text.match(/```json\s*([\s\S]*?)\s*```/);
  if (match && match[1]) {
    return match[1];
  }
  return text;
}

/**
 * Generate compliant copy alternatives with enhanced prompting
 */
export async function generateCopy(productInfo, style = 'energetic') {
  try {
    logger.info('Generating copy with Claude', { 
      product: productInfo.name,
      category: productInfo.category,
      style 
    });
    
    const prompt = buildCopyPrompt(productInfo, style);
    
    const message = await anthropic.messages.create({
      model: "claude-sonnet-4-5",
      max_tokens: 2048,
      temperature: 0.7, // Slight creativity
      messages: [
        {
          role: "user",
          content: prompt
        }
      ]
    });
    
    const contentText = message.content[0].text;
    const rawJson = extractJsonFromMarkdown(contentText);
    const suggestions = JSON.parse(rawJson);
    
    // Validate structure
    if (!Array.isArray(suggestions) || suggestions.length === 0) {
      throw new Error('Invalid suggestions format from Claude');
    }
    
    // Ensure all required fields exist
    const validatedSuggestions = suggestions.map((s, index) => ({
      headline: s.headline || `Headline ${index + 1}`,
      subhead: s.subhead || '',
      rationale: s.rationale || 'Generated by AI',
      complianceNotes: s.complianceNotes || 'Reviewed for compliance',
      style: style,
      category: productInfo.category
    }));
    
    logger.info('Copy generated successfully', { 
      count: validatedSuggestions.length,
      avgHeadlineLength: Math.round(
        validatedSuggestions.reduce((sum, s) => sum + s.headline.length, 0) / validatedSuggestions.length
      )
    });
    
    return validatedSuggestions;
  } catch (error) {
    logger.error('Copy generation failed', error);
    throw error;
  }
}

/**
 * Validate existing copy against compliance rules
 */
export async function validateCopy(text) {
  try {
    logger.info('Validating copy text', { length: text.length });
    
    const message = await anthropic.messages.create({
      model: "claude-sonnet-4-5",
      max_tokens: 1024,
      messages: [
        {
          role: "user",
          content: `Analyze this advertising copy for compliance issues.

COPY TO VALIDATE:
"${text}"

CHECK FOR:
1. Terms & conditions language (T&Cs, conditions apply, etc.)
2. Competition/contest language (win, enter, prize)
3. Unsubstantiated claims (best, only, guaranteed without proof)
4. Green/environmental claims
5. Charity partnership mentions
6. Price/discount language without context

Return JSON only:
{
  "isCompliant": boolean,
  "violations": [
    {
      "type": "prohibited_text | unsubstantiated_claim | ...",
      "severity": "error | warning",
      "message": "Clear explanation",
      "suggestion": "Alternative wording"
    }
  ],
  "score": 0-100
}`
        }
      ]
    });
    
    const rawJson = extractJsonFromMarkdown(message.content[0].text);
    const validation = JSON.parse(rawJson);
    
    logger.info('Copy validation complete', { 
      isCompliant: validation.isCompliant,
      violations: validation.violations?.length || 0
    });
    
    return validation;
  } catch (error) {
    logger.error('Copy validation failed', error);
    throw error;
  }
}

export default {
  generateCopy,
  validateCopy
};