import { create } from 'zustand';

const useAIStore = create((set) => ({
  // Layouts and copy generated by specific tools
  generatedLayouts: [],
  generatedCopy: [],
  
  // Assistant chat persistence
  assistantInput: '',
  assistantResults: null,

  // --- NEW: Persist Copy Tab Form Data ---
  copyFormData: {
    productName: '',
    category: 'beverages',
    features: '',
    style: 'energetic'
  },
  
  // Setters
  setGeneratedLayouts: (layouts) => set({ generatedLayouts: layouts }),
  setGeneratedCopy: (copy) => set({ generatedCopy: copy }),
  
  setAssistantInput: (input) => set({ assistantInput: input }),
  setAssistantResults: (results) => set({ assistantResults: results }),

  // --- NEW: Setter for Copy Form ---
  setCopyFormData: (updates) => set((state) => ({
    copyFormData: { ...state.copyFormData, ...updates }
  })),
}));

export default useAIStore;