import { create } from 'zustand';

const useAIStore = create((set) => ({
  // Layouts and copy generated by specific tools
  generatedLayouts: [],
  generatedCopy: [],
  
  // Assistant chat persistence
  assistantInput: '',
  assistantResults: null,
  
  // Setters
  setGeneratedLayouts: (layouts) => set({ generatedLayouts: layouts }),
  setGeneratedCopy: (copy) => set({ generatedCopy: copy }),
  
  // New setters for persistence
  setAssistantInput: (input) => set({ assistantInput: input }),
  setAssistantResults: (results) => set({ assistantResults: results }),
}));

export default useAIStore;